# crafit @Shinchan7222

from . import *

x = True


@bot.on(mew_cmd(pattern="galispam"))
async def _(event):
    while x != False:

        await event.delete()
        kek = event.chat_id
        await mewbot.send_message(kek, "TERIIIIII")
        await mewbot.send_message(kek, "MAAA KIIII")
        await mewbot.send_message(kek, "CHUTT MARUUUU")
        await mewbot.send_message(kek, "MADERRCHODD")
        await mewbot.send_message(kek, "BEHENN KEE LODEEE")
        await mewbot.send_message(kek, "TERIII MAAA")
        await mewbot.send_message(kek, "KOO AISAA CHODAAA")
        await mewbot.send_message(kek, "MADEERCHODD")
        await mewbot.send_message(kek, "KAALAAP GYII")
        await mewbot.send_message(kek, "TERII MAAA")
        await mewbot.send_message(kek, "TERAAA")
        await mewbot.send_message(kek, "KHANDAANN KO")
        await mewbot.send_message(kek, "ANDARRRR TKK")
        await mewbot.send_message(kek, "CHOD DALAAA")
        await mewbot.send_message(kek, "TERIIII")
        await mewbot.send_message(kek, "BEHENNN")
        await mewbot.send_message(kek, "ABHII MEREE")
        await mewbot.send_message(kek, "SEEEE")
        await mewbot.send_message(kek, "CHUDD RHI HAIII")
        await mewbot.send_message(kek, "MADERRCHODDD")
        await mewbot.send_message(kek, " TERIII")
        await mewbot.send_message(kek, "MAAA KIII")
        await mewbot.send_message(kek, "CHUTT MEE")
        await mewbot.send_message(kek, "HATHII KAA")
        await mewbot.send_message(kek, "LAUDAA")
        await mewbot.send_message(kek, "GHUSAA DIYAA")
        await mewbot.send_message(kek, "MADEERRCHODDD")
        await mewbot.send_message(kek, "RANDII")
        await mewbot.send_message(kek, "KAA")
        await mewbot.send_message(kek, "PILLAAA")
        await mewbot.send_message(kek, "BEHENCHODDD")
        await mewbot.send_message(kek, "TERIII")
        await mewbot.send_message(kek, "BEHENN")
        await mewbot.send_message(kek, "KIII")
        await mewbot.send_message(kek, "CHUTTT")
        await mewbot.send_message(kek, "MEEE")
        await mewbot.send_message(kek, "TOWERRR")
        await mewbot.send_message(kek, "GHUSAA DIYAA")
        await mewbot.send_message(kek, "MADERRRCHODD")
        await mewbot.send_message(kek, "TERAAA")
        await mewbot.send_message(kek, "BAAAP")
        await mewbot.send_message(kek, "HUINN")
        await mewbot.send_message(kek, "BSDKKKK")
        await mewbot.send_message(kek, "GANDD")
        await mewbot.send_message(kek, "MARR")
        await mewbot.send_message(kek, "MARRR")
        await mewbot.send_message(kek, "KEEE")
        await mewbot.send_message(kek, "ZINDAGIIII")
        await mewbot.send_message(kek, "ANDHERIII")
        await mewbot.send_message(kek, "KARRRR")
        await mewbot.send_message(kek, "DUGAAA")
        await mewbot.send_message(kek, "MADERRRCHODDD")
        await mewbot.send_message(kek, "BEHENNN")
        await mewbot.send_message(kek, "KEEE")
        await mewbot.send_message(kek, "LODEEE")
        await mewbot.send_message(kek, "AISAAA")
        await mewbot.send_message(kek, "CHODUGAAA")
        await mewbot.send_message(kek, "BSDKKK")
        await mewbot.send_message(kek, "PHIRRR")
        await mewbot.send_message(kek, "SEEE")
        await mewbot.send_message(kek, "KISIII")
        await mewbot.send_message(kek, "SEEE GANDD")
        await mewbot.send_message(kek, " MARANEE")
        await mewbot.send_message(kek, "KEE")
        await mewbot.send_message(kek, "LAYAKKK")
        await mewbot.send_message(kek, "NAHII BACHEGAAA")
        await mewbot.send_message(kek, "BAAAP")
        await mewbot.send_message(kek, "SEEE")
        await mewbot.send_message(kek, "PANGAA")
        await mewbot.send_message(kek, "LIYA HAIII")
        await mewbot.send_message(kek, "BSDKK TUUU")
        await mewbot.send_message(kek, "ANDARRR TAK")
        await mewbot.send_message(kek, "CHUDEGGAAA")
        await mewbot.send_message(kek, "TERIII")
        await mewbot.send_message(kek, "MAAAA")
        await mewbot.send_message(kek, "KAAA RAPEE")
        await mewbot.send_message(kek, "KARR DIYAA")
        await mewbot.send_message(kek, "MADERRCHODDD")
        await mewbot.send_message(kek, "BEHENCHODD")
        await mewbot.send_message(kek, "TERAAA")
        await mewbot.send_message(kek, "ASLIII")
        await mewbot.send_message(kek, "BAAAP MAINN")
        await mewbot.send_message(kek, "HI HUINNN")
        await mewbot.send_message(kek, "BSDKK")
        await mewbot.send_message(kek, "TERI MAA")
        await mewbot.send_message(kek, "KOO KOTHEE")
        await mewbot.send_message(kek, "PE CHODAA")
        await mewbot.send_message(kek, "THAA GHODII BANAKEE")
        await mewbot.send_message(kek, "JAKEEE")
        await mewbot.send_message(kek, "PUCHHH APNI")
        await mewbot.send_message(kek, "APNI")
        await mewbot.send_message(kek, "SAMJHAA LAWDE")
        await mewbot.send_message(kek, "MAAA SEE��")
        await mewbot.send_message(kek, "TERI ASLII")
        await mewbot.send_message(kek, "BAAAP")
        await mewbot.send_message(kek, "MAIN HI HUINN")
        await mewbot.send_message(kek, "MERAA NAJAYAZ�不")
        await mewbot.send_message(kek, "BETA HAI TUU")
